name: Uptime Monitor
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run uptime monitor
        id: monitor
        uses: fragmetal/uptime@main
        with:
          sites: |
            https://example.com
            https://your-other-site.com
          data-file: 'src/lib/uptime-data.json'
          
      - name: Calculate uptime stats
        if: always()
        run: |
          node <<EOF
          const fs = require('fs');
          const path = require('path');
          
          const dataPath = path.join(process.env.GITHUB_WORKSPACE, 'src/lib/uptime-data.json');
          const historyPath = path.join(process.env.GITHUB_WORKSPACE, 'src/lib/uptime-history.json');
          
          let currentData = require(dataPath);
          let historyData = fs.existsSync(historyPath) ? require(historyPath) : {};
          
          // Update history for each site
          Object.entries(currentData).forEach(([url, stats]) => {
            if (!historyData[url]) {
              historyData[url] = {
                totalChecks: 0,
                successfulChecks: 0,
                history: []
              };
            }
            
            historyData[url].totalChecks += 1;
            if (stats.up) historyData[url].successfulChecks += 1;
            historyData[url].history.push({
              time: stats.time,
              up: stats.up,
              ping: stats.ping
            });
            
            // Keep only the last 100 entries
            if (historyData[url].history.length > 100) {
              historyData[url].history.shift();
            }
            
            // Add uptime percentage to current data
            currentData[url].uptimePercentage = Math.round(
              (historyData[url].successfulChecks / historyData[url].totalChecks) * 100
            );
          });
          
          fs.writeFileSync(dataPath, JSON.stringify(currentData, null, 2));
          fs.writeFileSync(historyPath, JSON.stringify(historyData, null, 2));
          EOF
      
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add src/lib/uptime-*.json
          git commit -m "Update uptime data [skip ci]" || exit 0
          git push
