# .github/workflows/uptime-check.yml
name: Uptime Check
on:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes (minimum interval for GitHub Actions)
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm install axios fz
          
      - name: Run uptime checks
        run: |
          node src/lib/github.js
          
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add src/lib/uptime-data.json
          git commit -m "Update uptime data [skip ci]" || echo "No changes to commit"
          git push