name: Uptime Monitor
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check websites
        run: |
          # Create a simple uptime checker script
          node <<EOF
          const axios = require('axios');
          const fs = require('fs');
          
          const sites = [
            'Power#3745',
            'https://507ab6b2-a51f-490e-9363-960390d518db-00-3pgweb6uweae0.pike.replit.dev/'
          ];
          
          const results = {};
          
          async function checkSite(url) {
            try {
              const start = Date.now();
              const response = await axios.get(url, { timeout: 5000 });
              return {
                up: response.status === 200,
                ping: Date.now() - start,
                time: new Date().toISOString()
              };
            } catch (error) {
              return {
                up: false,
                ping: null,
                time: new Date().toISOString()
              };
            }
          }
          
          (async () => {
            for (const url of sites) {
              results[url] = await checkSite(url);
            }
            fs.writeFileSync('src/lib/uptime-data.json', JSON.stringify(results, null, 2));
          })();
          EOF
          
      - name: Install dependencies
        run: npm install axios
      
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add src/lib/uptime-data.json
          git commit -m "Update uptime data [skip ci]" || exit 0
          git push
